// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nkwsvsmmzvukdghlyxpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rd3N2c21tenZ1a2RnaGx5eHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MzExMzQsImV4cCI6MjA3NTEwNzEzNH0.BQW6poa2Jo_55X4GfkEcWLQRqeqcmC0ERCI5DeUqY58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Garante que a sessão seja persistida
    storage: typeof window !== 'undefined' ? window.localStorage : undefined, // Usa localStorage no navegador
  }
});